changing the "test" conditional to work in solaris

diff --git a/rc.ido2db.in b/rc.ido2db.in
--- a/rc.ido2db.in
+++ b/rc.ido2db.in
@@ -110,9 +110,10 @@ ido2db_procs ()
 
 printstatus_ido2db()
 {
-	if status_ido2db $1 $2; then
-		echo "$servicename (pid $Ido2dbPID) is running..."
-	elif test $? == 2; then
+     if status_ido2db $1 $2; then
+        ido2db_procs
+	echo "$servicename (pid $ido2dbPID) is running with $PCHILD child procs $PID_LIST..."
+	elif test $? -eq 2; then # this command will fail on solaris the "==" needed to be replaced with "-eq"
 		echo "$servicename is not running but subsystem locked"
 	else
 		echo "$servicename is not running"
